import { useState } from "react";

const Game = [
    {
        name: "ブルーアーカイブ -Blue Archive-",
        genre: ["RPG"],
        model: "iOS,Android",
        developer: "Nexon Games",
        seller: "Yostar, Inc.",
        link: "https://bluearchive.jp/",
        download: 13000000,
        year: 2021,
        month: 2,
        season: "冬",
        image: "Game-Genre/RPG/ブルーアーカイブ.jpg"
    },
    {
        name: "アズールレーン",
        genre: ["RPG","シューティング"],
        model: "iOS,Android",
        developer: "Shanghai Manjuu/Xiamen Yongshi",
        seller: "Yostar, Inc.",
        link: "https://www.azurlane.jp/",
        download: 40000000,
        year: 2017,
        month: 9,
        season: "夏",
        image: "Game-Genre/RPG/アズールレーン.jpg"
    },
    {
        name: "Fate/Grand Order",
        genre: ["RPG"],
        model: "iOS,Android",
        developer: "ディライトワークス",
        seller: "Aniplex Inc.",
        link: "https://www.fate-go.jp/",
        download: 80000000,
        year: 2015,
        month: 7,
        season: "夏",
        image: "Game-Genre/RPG/Fate Grand Order.jpg"
    },
    {
        name: "ファイナルファンタジーXIV",
        genre: ["RPG"],
        model: "PS4,PS5,PC,XboxSX",
        developer: "SQUARE ENIX",
        seller: "SQUARE ENIX",
        link: "https://www.finalfantasyxiv.com/freetrial/?utm_source=accesstrade&utm_medium=affiliate&utm_campaign=jp-freetrial&utm_content=affiliate-1&atnct=seff14_0100mmzp009j64-ff151fed48cbe91e97418554175f1e60",
        download: 30000000,
        year: 2013,
        month: 8,
        season: "夏",
        image: "Game-Genre/RPG/ファイナルファンタジーXIV.jpg"
    },
    {
        name: "ヘブンバーンズレッド",
        genre: ["RPG"],
        model: "iOS.Android,PC",
        developer: "WFS, Inc./Key",
        seller: "WFS, Inc./Yostar, Inc.",
        link: "https://heaven-burns-red.com/",
        download: 6000000,
        year: 2022,
        month: 2,
        season: "冬",
        image: "Game-Genre/RPG/ヘブンバーンズレッド.jpg"
    },
    {
        name: "勝利の女神：NIKKE",
        genre: ["RPG","アクション","シューティング"],
        model: "iOS.Android,PC",
        developer: "Shift Up",
        seller: "Level Infinite",
        link: "https://nikke-jp.com/",
        download: 50000000,
        year: 2022,
        month: 11,
        season: "秋",
        image: "Game-Genre/RPG/勝利の女神NIKKE.jpg"
    },
    {
        name: "PSO2 ニュージェネシス",
        genre: ["RPG"],
        model: "Switch,PS4,PC",
        developer: "SEGA",
        seller: "SEGA",
        link: "https://lp.pso2.jp/",
        download: 12000000,
        year: 2021,
        month: 6,
        season: "夏",
        image: "Game-Genre/RPG/PSO2 ニュージェネシス.jpg"
    },
    {
        name: "グランブルーファンタジー",
        genre: ["RPG"],
        model: "iOS.Android,PC",
        developer: "Cygames, Inc.",
        seller: "Cygames, Inc.",
        link: "https://granbluefantasy.jp/",
        download: 39000000,
        year: 2014,
        month: 3,
        season: "冬",
        image: "Game-Genre/RPG/グランブルーファンタジー.jpg"
    },
    {
        name: "崩壊：スターレイル",
        genre: ["RPG"],
        model: "iOS.Android,PS5,PC",
        developer: "miHoYo",
        seller: "COGNOSPHERE PTF. LTD.",
        link: "https://hsr.hoyoverse.com/ja-jp/",
        download: 160000000,
        year: 2023,
        month: 4,
        season: "春",
        image: "Game-Genre/RPG/崩壊スターレイル.jpg"
    },
    {
        name: "プリンセスコネクト!Re:Dive",
        genre: ["RPG"],
        model: "iOS,Android,PC",
        developer: "Cygames, Inc.",
        seller: "Cygames, Inc.",
        link: "https://priconne-redive.jp/",
        download: 35000000,
        year: 2018,
        month: 2,
        season: "冬",
        image: "Game-Genre/RPG/プリンセスコネクト!Re Dive.jpg"
    },//ここまで10番目
    {
        name: "ぷよぷよ!!クエスト",
        genre: ["RPG","パズル"],
        model: "iOS,Android",
        developer: "SEGA",
        seller: "SEGA",
        link: "https://puyopuyoquest.sega-net.com/",
        download: 30000000,
        year: 2013,
        month: 4,
        season: "春",
        image: "Game-Genre/RPG/ぷよぷよ!!クエスト.jpg"
    },
    {
        name: "魔法少女まどか☆マギカ Magia Exedra",
        genre: ["RPG"],
        model: "iOS,Android,PC",
        developer: "Pokelabo, Inc./f4samurai, Inc.",
        seller: "Aniplex, Inc.",
        link: "https://madoka-exedra.com/",
        download: 5000000,
        year: 2025,
        month: 3,
        season: "冬",
        image: "Game-Genre/RPG/魔法少女まどか☆マギカ Magia Exedra.jpg"
    },
    {
        name: "原神",
        genre: ["RPG","アクション"],
        model: "iOS,Android,PS4,PS5,XboxSX,PC",
        developer: "miHoYo",
        seller: "COGNOSPHERE PTE. LTD.",
        link: "https://genshin.hoyoverse.com/ua/pc-download?utm_source=JP_Macan_JP_PC_New&hoyotrace_channel=macan_channel&lang=ja-jp&trackingId=21228281338057&transaction_id=2026013171b91769867393155404a&gid=212_3574_214",
        download: 225000000,
        year: 2020,
        month: 9,
        season: "夏",
        image: "Game-Genre/RPG/原神.jpg"
    },
    {
        name: "チェインクロニクル",
        genre: ["RPG","シューティング"],
        model: "iOS,Android",
        developer: "SEGA",
        seller: "SEGA",
        link: "https://chronicle.sega-net.com/",
        download: 27000000,
        year: 2016,
        month: 11,
        season: "秋",
        image: "Game-Genre/RPG/チェインクロニクル.jpg"
    },
    {
        name: "ペルソナ5: The Phantom X",
        genre: ["RPG"],
        model: "iOS,Android,PC",
        developer: "Black Wings Game Studio",
        seller: "SEGA",
        link: "https://p5x.jp/",
        download: 5000000,
        year: 2025,
        month: 6,
        season: "夏",
        image: "Game-Genre/RPG/ペルソナ5 The Phantom X.jpg"
    },
    {
        name: "レスレリアーナのアトリエ",
        genre: ["RPG"],
        model: "iOS,Android,PC",
        developer: "Gust/Team NINJA",
        seller: "コーエーテクモゲームス",
        link: "https://www.gamecity.ne.jp/atelier/resleriana/",
        download: 5000000,
        year: 2023,
        month: 9,
        season: "夏",
        image: "Game-Genre/RPG/レスレリアーナのアトリエ.jpg"
    },
    {
        name: "対魔忍RPG",
        genre: ["RPG"],
        model: "Android,PC",
        developer: "Lilith Soft",
        seller: "インフィニブレイン",
        link: "https://games.dmm.com/detail/taimanin_rpg",
        download: 2500000,
        year: 2018,
        month: 9,
        season: "夏",
        image: "Game-Genre/RPG/対魔忍RPG.jpg"
    },
    {
        name: "転生したらスライムだった件 魔王と竜の建国譚",
        genre: ["RPG"],
        model: "iOS,Android",
        developer: "WFS, Inc.",
        seller: "Bandai Namco Entertainment Inc.",
        link: "https://ten-sura-m.bn-ent.net/",
        download: 9000000,
        year: 2021,
        month: 10,
        season: "秋",
        image: "Game-Genre/RPG/転生したらスライムだった件 魔王と竜の建国譚.jpg"
    },
    {
        name: "ドラゴンポーカー",
        genre: ["RPG"],
        model: "iOS,Android",
        developer: "Asobism.Co.,Ltd",
        seller: "Asobism.Co.,Ltd",
        link: "https://www.asobism.co.jp/social/dragonpoker/",
        download: 9000000,
        year: 2013,
        month: 5,
        season: "春",
        image: "Game-Genre/RPG/ドラゴンポーカー.jpg"
    },
    {
        name: "メメントモリ",
        genre: ["RPG"],
        model: "iOS,Android,PC",
        developer: "Bank of Innovation, Inc.",
        seller: "Bank of Innovation, Inc.",
        link: "https://mememori-game.com/",
        download: 4500000,
        year: 2022,
        month: 10,
        season: "秋",
        image: "Game-Genre/RPG/メメントモリ.jpg"
    },//ここまで20番目
    {
        name: "D×2 真・女神転生リベレーション",
        genre: ["RPG"],
        model: "iOS,Android",
        developer: "SEGA",
        seller: "SEGA",
        link: "https://d2-megaten-l.sega.jp/",
        download: 15000000,
        year: 2018,
        month: 1,
        season: "冬",
        image: "Game-Genre/RPG/D×2 真・女神転生リベレーション.jpg"
    },
    {
        name: "白猫プロジェクト NEW WORLD’S",
        genre: ["RPG","アクション"],
        model: "iOS,Android",
        developer: "COLOPL, Inc.",
        seller: "COLOPL, Inc.",
        link: "https://colopl.co.jp/shironekoproject/",
        download: 120000000,
        year: 2014,
        month: 7,
        season: "夏",
        image: "Game-Genre/RPG/白猫プロジェクト NEW WORLD’S.jpg"
    },
    {
        name: "モンスターストライク",
        genre: ["RPG","アクション"],
        model: "iOS,Android",
        developer: "MIXI",
        seller: "MIXI",
        link: "https://www.monster-strike.com/",
        download: 65000000,
        year: 2013,
        month: 10,
        season: "秋",
        image: "Game-Genre/RPG/モンスト.jpg"
    },
    {
        name: "ゼンレスゾーンゼロ",
        genre: ["RPG","アクション"],
        model: "iOS,Android,PS5,XboxSX,PC",
        developer: "HoYoverse",
        seller: "COGNOSPHERE PTE. LTD.",
        link: "https://zenless.hoyoverse.com/ua?utm_source=ua&utm_medium=MacanPC&utm_campaign=ZZZ-JP-PC-1-new-MacanPC-20241023-S2S&trackingId=21228288319014&transaction_id=20260201b56b1769932388161359a&lang=ja-jp&gid=212_3574_214",
        download: 100000000,
        year: 2024,
        month: 7,
        season: "夏",
        image: "Game-Genre/RPG/ゼンレスゾーンゼロ.jpg"
    },
    {
        name: "ガーディアンテイルズ",
        genre: ["RPG"],
        model: "iOS,Android,Switch",
        developer: "KONG STUDIO INC",
        seller: "KONG STUDIOS INC",
        link: "https://guardiantales.jp/",
        download: 30000000,
        year: 2021,
        month: 10,
        season: "秋",
        image: "Game-Genre/RPG/ガーディアンテイルズ.jpg"
    },
    {
        name: "共闘ことばRPG コトダマン",
        genre: ["RPG"],
        model: "iOS,Android",
        developer: "MIXI",
        seller: "MIXI",
        link: "https://kotodaman.jp/",
        download: 6500000,
        year: 2018,
        month: 4,
        season: "春",
        image: "Game-Genre/RPG/共闘ことばRPG コトダマン.jpg"
    },
    {
        name: "ファイナルファンタジーVII エバークライシス",
        genre: ["RPG"],
        model: "iOS,Android,PC",
        developer: "Applibot, Inc.",
        seller: "SQUARE ENIX",
        link: "https://jp.ffviiec.com/",
        download: 12000000,
        year: 2023,
        month: 9,
        season: "夏",
        image: "Game-Genre/RPG/ファイナルファンタジーVII エバークライシス.jpg"
    },
    {
        name: "ラストクラウディア",
        genre: ["RPG"],
        model: "iOS,Android,PC",
        developer: "AIDIS Inc.",
        seller: "AIDIS Inc.",
        link: "https://lastcloudia.com/",
        download: 7000000,
        year: 2019,
        month: 4,
        season: "春",
        image: "Game-Genre/RPG/ラストクラウディア.jpg"
    },
    {
        name: "ユミアのアトリエ ～追憶の錬金術士と幻創の地～",
        genre: ["RPG"],
        model: "Switch,PS4,PS5,XboxSX,XboxOne,PC",
        developer: "Gust",
        seller: "コーエーテクモゲームス",
        link: "https://atelier.games/yumia/jp/",
        download: 500000,
        year: 2025,
        month: 3,
        season: "冬",
        image: "Game-Genre/RPG/ユミアのアトリエ ～追憶の錬金術士と幻創の地～.jpg"
    },
    {
        name: "ドラゴンクエストウォーク",
        genre: ["RPG"],
        model: "iOS,Android",
        developer: "コロプラ",
        seller: "SQUARE ENIX",
        link: "https://www.dragonquest.jp/walk/",
        download: 35000000,
        year: 2019,
        month: 9,
        season: "夏",
        image: "Game-Genre/RPG/ドラゴンクエストウォーク.png"
    },//ここまで30番目
    {
        name: "アナザーエデン 時空を超える猫",
        genre: ["RPG"],
        model: "iOS,Android,PC",
        developer: "WFS, Inc.",
        seller: "WFS, Inc.",
        link: "https://another-eden.jp/",
        download: 15000000,
        year: 2017,
        month: 4,
        season: "春",
        image: "Game-Genre/RPG/アナザーエデン 時空を超える猫.jpg"
    },
    {
        name: "ドラゴンクエストX オンライン",
        genre: ["RPG"],
        model: "iOS,Android,WiiU,Switch,PS4,PC",
        developer: "SQUARE ENIX",
        seller: "SQUARE ENIX",
        link: "https://www.dqx.jp/",
        download: 6000000,
        year: 2012,
        month: 8,
        season: "夏",
        image: "Game-Genre/RPG/ドラゴンクエストX オンライン.png"
    },
    {
        name: "WIND BREAKER 不良たちの英雄譚",
        genre: ["RPG"],
        model: "iOS,Android,PC",
        developer: "Aiming",
        seller: "講談社",
        link: "https://www.wb-rebelheroes.com/",
        download: 2000000,
        year: 2025,
        month: 3,
        season: "冬",
        image: "Game-Genre/RPG/WIND BREAKER 不良たちの英雄譚.jpg"
    },
    {
        name: "放置少女～百花繚乱の萌姫たち～",
        genre: ["RPG","シミュレーション"],
        model: "iOS,Android,PC",
        developer: "C4 CONNECT Inc.",
        seller: "C4 CONNECT K.K",
        link: "https://hcsj.c4connect.co.jp/home",
        download: 30000000,
        year: 2017,
        month: 3,
        season: "冬",
        image: "Game-Genre/RPG/放置少女～百花繚乱の萌姫たち～.jpg"
    },
    {
        name: "ラストオリジン",
        genre: ["RPG"],
        model: "iOS,Android,PC",
        developer: "SmartJoy",
        seller: "GOP CO., Ltd.",
        link: "https://www.last-origin.com/",
        download: 4000000,
        year: 2020,
        month: 5,
        season: "春",
        image: "Game-Genre/RPG/ラストオリジン.jpg"
    },
    {
        name: "",
        genre: ["RPG"],
        model: "",
        developer: "",
        seller: "",
        link: "",
        download: 35000000,
        year: 2019,
        month: 9,
        season: "夏",
        image: "Game-Genre/RPG/.jpg"
    },
    {
        name: "",
        genre: ["RPG"],
        model: "",
        developer: "",
        seller: "",
        link: "",
        download: 35000000,
        year: 2019,
        month: 9,
        season: "夏",
        image: "Game-Genre/RPG/.jpg"
    },
    {
        name: "",
        genre: ["RPG"],
        model: "",
        developer: "",
        seller: "",
        link: "",
        download: 35000000,
        year: 2019,
        month: 9,
        season: "夏",
        image: "Game-Genre/RPG/.jpg"
    },
    {
        name: "",
        genre: ["RPG"],
        model: "",
        developer: "",
        seller: "",
        link: "",
        download: 35000000,
        year: 2019,
        month: 9,
        season: "夏",
        image: "Game-Genre/RPG/.jpg"
    },
    {
        name: "",
        genre: ["RPG"],
        model: "",
        developer: "",
        seller: "",
        link: "",
        download: 35000000,
        year: 2019,
        month: 9,
        season: "夏",
        image: "Game-Genre/RPG/.jpg"
    },//ここまで40番目
];
export default function App() {
  return (
    <div>
      <h1>ゲーム 全世界累計ダウンロード数マップ (制作段階中)</h1>
    </div>
  );
}